version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"            # host:container
    volumes:
      - ./:/var/www/html     # live-reload
    environment:
      APP_ENV: development
      DB_HOST: db
      DB_USER: user
      DB_PASS: secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
